# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A workflow to build fresh binaries.
# Builds ffmpeg and ffprobe on all OS & CPU combinations, then optionally
# attaches them to a release.
name: Build

on:
  # Runs when called from another workflow, such as the release or test
  # workflows.
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      # If true, start a debug SSH server on failures.
      debug:
        required: false
        type: boolean
        default: false
      # If true, enable self-hosted runners in the build matrix.
      self_hosted:
        required: false
        type: boolean
        default: false

  # Runs on manual trigger.
  workflow_dispatch:
    inputs:
      # If true, start a debug SSH server on failures.
      debug:
        required: false
        type: boolean
        default: false
      # If true, enable self-hosted runners in the build matrix.
      self_hosted:
        required: false
        type: boolean
        default: false


# NOTE: The versions of the software we build are stored in versions.txt.

# By default, run all commands in a bash shell.  On Windows, the default would
# otherwise be powershell.  Each shell command should begin with "set -e" (to
# make any failed command fail the script immediately) and "set -x" (to log
# what commands are being run).
defaults:
  run:
    shell: bash

jobs:
  # Configure the build matrix based on inputs.  The list of objects in the
  # build matrix contents can't be changed by conditionals, but it can be
  # computed by another job and deserialized.
  matrix_config:
    runs-on: ubuntu-latest
    outputs:
      MATRIX: ${{ steps.configure.outputs.MATRIX }}
    steps:
      - uses: actions/checkout@v6
        with:
          path: repo-src
          ref: ${{ inputs.ref || github.ref }}
          persist-credentials: false

      - name: Configure Build Matrix
        id: configure
        shell: node {0}
        run: |
          const fs = require('fs');
          const enableDebug = ${{ inputs.debug }};
          const enableSelfHosted = ${{ inputs.self_hosted }};

          // Use enableSelfHosted to decide what the build matrix below should
          // include.
          const buildMatrix = JSON.parse(fs.readFileSync("${{ github.workspace }}/repo-src/build-matrix.json"));
          const {hosted, selfHosted} = buildMatrix;
          const matrix = enableSelfHosted ? hosted.concat(selfHosted) : hosted;

          // Output a JSON object consumed by the build matrix below.
          fs.appendFileSync(
              process.env['GITHUB_OUTPUT'],
              `MATRIX=${ JSON.stringify(matrix) }\n`);

          // Log the outputs, for the sake of debugging this script.
          console.log({enableDebug, enableSelfHosted, matrix});

  # On several different hosts, build ffmpeg's dependencies, then ffmpeg itself.
  # The deps are all built as static libraries.
  build:
    needs: matrix_config
    strategy:
      # Let other matrix entries complete, so we have all results on failure
      # instead of just the first failure.
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.matrix_config.outputs.MATRIX) }}

    name: Build ${{ matrix.os_name }} ${{ matrix.target_arch }} ${{ matrix.container }}
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
      # Access to the host filesystem is required to patch the environment for
      # Alpine Linux support.  See the first Alpine step below for details.
      volumes:
        - /:/host

    steps:
      - name: Add msys2 to the Windows path
        if: runner.os == 'Windows'
        run: |
          # At this point, we're running Git Bash.  After this step, we will be
          # running msys bash, just as we would be when debugging via SSH with
          # mxschmitt/action-tmate.
          echo "C:\\msys64\\usr\\bin" >> "$GITHUB_PATH"
          echo "C:\\msys64\\mingw64\\bin" >> "$GITHUB_PATH"

      # This is how we convince GitHub Actions Runner to run an Alpine Linux
      # container.  We have to mask the fact that it's Alpine, install NodeJS,
      # then patch the Alpine version of NodeJS in over the one that ships with
      # GitHub Actions.  This is because GitHub doesn't officially support
      # Alpine and because they hard-code the path to NodeJS in Node-based
      # actions.
      # See https://github.com/actions/runner/issues/801#issuecomment-2976165281
      - name: Patch native Alpine NodeJS into Runner environment
        if: startsWith(matrix.container, 'alpine')
        run: |
          echo "OS Release:"
          cat /etc/os-release

          # GitHub Actions Runner will exclude Alpine arm64 runners before
          # executing any JavaScript action.  So we have to pretend we aren't
          # that. See:
          #  - https://github.com/actions/runner/blob/40dd583/src/Runner.Worker/Handlers/StepHost.cs#L283
          #  - https://github.com/actions/runner/issues/801
          #  - https://github.com/actions/runner/issues/801#issuecomment-1374967227
          #  - https://github.com/actions/runner/issues/801#issuecomment-2394425757
          if [[ "${{ matrix.target_arch }}" == "arm64" ]]; then
            sed -i "s:^ID=alpine:ID=NotpineForGHA:" /etc/os-release
          fi

          # Install native Alpine NodeJS
          apk add nodejs

          START_TS=$(date +%s)

          # Paths as of 2026-03-10:
          #   GitHub-hosted on x64: /host/home/runner/actions-runner/cached/externals
          #   GitHub-hosted on arm64: /host/home/runner/actions-runner/cached/2.332.0/externals
          #   Self-hosted with myoung34/github-runner: /host/actions-runner/externals
          # Instead of hardcoding paths, which seem to change on occasion,
          # locate them dynamically.

          # Map the filesystem with plocate.
          apk add plocate
          updatedb

          # There may be multiple versions installed.  Assume we keep the
          # "externals" convention noted above.
          ALL_NODE_BINARIES=$(plocate externals | grep '/bin/node$')
          echo "Node binaries:"
          echo "$ALL_NODE_BINARIES"

          ALL_NODE_FOLDERS=$(echo "$ALL_NODE_BINARIES" | sed -e 's@/bin/node@@')
          echo "Node folders:"
          echo "$ALL_NODE_FOLDERS"

          for FOLDER in $ALL_NODE_FOLDERS; do
            echo "Patching NodeJS in $FOLDER"
            rm -rf "$FOLDER"/*
            mkdir "$FOLDER"/bin
            ln -s /usr/bin/node "$FOLDER"/bin/node
          done

          END_TS=$(date +%s)
          echo "Node patch took $((END_TS - START_TS)) seconds."

        shell: sh  # No bash in Alpine by default

      - name: Install Alpine Linux deps
        if: startsWith(matrix.container, 'alpine')
        run: apk add bash npm sudo
        shell: sh  # No bash in Alpine until after this command

      - name: Install Ubuntu Linux deps
        if: startsWith(matrix.container, 'ubuntu')
        # Sudo is needed by the first build script, but isn't in the default
        # container image for Ubuntu.
        run: apt -y update && apt -y upgrade && apt -y install sudo

      - uses: actions/checkout@v6
        with:
          path: repo-src
          ref: ${{ inputs.ref || github.ref }}
          persist-credentials: false

      - name: Install OS packages
        run: ./repo-src/build-scripts/00-packages.sh

      - name: Install libvpx
        run: ./repo-src/build-scripts/01-libvpx.sh

      - name: Install SVT-AV1
        run: ./repo-src/build-scripts/02-svt-av1.sh

      - name: Install x264
        run: ./repo-src/build-scripts/03-x264.sh

      - name: Install x265
        run: ./repo-src/build-scripts/04-x265.sh

      - name: Install lame
        run: ./repo-src/build-scripts/05-lame.sh

      - name: Install opus
        run: ./repo-src/build-scripts/06-opus.sh

      - name: Install mbedtls
        run: ./repo-src/build-scripts/07-mbedtls.sh

      - name: Build ffmpeg and ffprobe
        run: ./repo-src/build-scripts/90-ffmpeg.sh

      - name: Prepare assets
        run: |
          set -e
          set -x

          mkdir assets
          SUFFIX="-${{ matrix.os_name }}-${{ matrix.target_arch }}${{ matrix.exe_ext}}"
          echo "SUFFIX=$SUFFIX" >> "$GITHUB_ENV"
          cp ffmpeg/ffmpeg assets/ffmpeg"$SUFFIX"
          cp ffmpeg/ffprobe assets/ffprobe"$SUFFIX"

          # Show sizes and MD5 sums that can be verified by users later if they
          # want to check for authenticity.
          cd assets
          wc -c *
          md5sum *

      # This makes it possible to debug failures in the next step by
      # downloading binaries that fail the check for static linkage.
      - name: Upload assets as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: binaries${{ env.SUFFIX }}
          path: assets/*

      - name: Check that executables are static
        run: ./repo-src/build-scripts/99-check-static.sh

      # Because we had to break Alpine detection to work around runner
      # restrictions, we also have to manually install Alpine deps for tmate.
      # The action below can't tell what distro we are on, and tries to use
      # apt-get if we let it install deps.
      - name: Alpine Debug Prep
        if: failure() && inputs.debug && startsWith(matrix.container, 'alpine') && matrix.target_arch == 'arm64'
        run: |
          # These are tmate's direct dependencies according to the action below.
          apk add openssh-client xz bash

          # Now install tmate itself.
          TMATE_LINUX_VERSION=2.4.0
          TMATE_ARCH=arm64v8
          curl -Lo tmate.tar.xz \
              https://github.com/tmate-io/tmate/releases/download/${TMATE_LINUX_VERSION}/tmate-${TMATE_LINUX_VERSION}-static-linux-${TMATE_ARCH}.tar.xz
          tar xf tmate.tar.xz
          install -m 755 tmate-${TMATE_LINUX_VERSION}-static-linux-${TMATE_ARCH}/tmate /usr/bin/tmate
          rm -rf tmate-${TMATE_LINUX_VERSION}-static-linux-${TMATE_ARCH}/

      - name: Debug
        uses: mxschmitt/action-tmate@v3.23
        with:
          limit-access-to-actor: true
          # See comment above on "Alpine Debug Prep".
          install-dependencies: ${{ !(startsWith(matrix.container, 'alpine') && matrix.target_arch == 'arm64') }}
        if: failure() && inputs.debug
